spring:

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

#mybatis:
#  config-location: classpath:mybatis/config/mapper-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    org.springframework.security: DEBUG
